name: Compile & Upload ACL Policy
description: Action that will compile repo policy and update globally
inputs:
  local-acl-path:
    required: true
    description: "Path to the ACL recipe"
  local-acl-remote-path:
    required: true
    description: "Path to the ACL recipe"
  local-acl-prefix:
    required: true
    description: "Path to prepend to each rule in repo"
  remote-acl-policies-path:
    required: true
    description: "Path to the directory where ACL policies are stored"
    default: .acl
  global-acl-remote-path:
    required: true
    description: "Remote path where the global-acl is stored"
runs:
  using: composite
  steps:
    - name: Setup Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
    - run: pip3 install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Download ACL Policy
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.local-acl-artifact-name }}
        path: /tmp/
    - name: Upload Local ACL Policy
      shell: bash
      run: python3 ${{ github.action_path }}/main.py generate-local-acl --acl-file ${{ inputs.local-acl-path }} --acl-prefix ${{ inputs.local-acl-prefix }} --output-path ${{ inputs.local-acl-remote-path }}
    - name: Upload Local ACL Policy
      shell: bash
      run: python3 ${{ github.action_path }}/main.py generate-global-acl --acl-path ${{ inputs.remote-acl-policies-path }} --output-path ${{ inputs.global-acl-remote-path }}