name: publici-release-artifact
on:
  workflow_call:
    inputs:
      package: 
        required: true
        type: string
      artifact_id:
        required: true
        type: string
      public:
        required: false
        type: boolean
        default: false
      type:
        required: true
        type: string
env:
  WORKLOAD_POOL: projects/318349477291/locations/global/workloadIdentityPools/publici-share-github/providers/publici-share-github
  SERVICE_ACCOUNT: gh-actions@publici-apps.iam.gserviceaccount.com
  BUCKET_NAME: publici-artifacts
  ARTIFACT_DIR: /tmp/release/
  TYPE: |
    ${{
      fromJson('{
        "terraform-modules": "terraform"
      }')[github.event.repository.name]
    }}
jobs:
  validate-inputs:
    runs-on: ubuntu-22.04
    steps:
      - id: validate-inputs
        shell: python
        run: |
          allowed = {
            "terraform-modules": "terraform"
          }

          expected = allowed[github.event.repository.name]

          if inputs.type != expected:
            print("Invalid package type: " + inputs.type)
            exit(1)
  release-artifact:
    runs-on: ubuntu-latest
    needs: validate-inputs
    steps:
      - id: gcp-authenticate
        uses: google-github-actions/auth@v0
        with: 
          workload_identity_provider: ${{ env.WORKLOAD_POOL }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
      - id: gcp-authenticate
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ env.WORKLOAD_POOL }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
      - id: download-asset
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_id }}
          path: /tmp/release/
      - id: upload-release-asset
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: /tmp/release/
          destination: |
            ${{ env.BUCKET_NAME }}/${{ inputs.type }}/${{ inputs.package }}/${{ inputs.artifact_id }}
