name: publici-release-artifact
on:
  workflow_call:
    inputs:
      package: 
        required: true
        type: string
      artifact_id:
        required: true
        type: string
      public:
        required: false
        type: boolean
        default: false
      type:
        required: true
        type: string
jobs:
  release-artifact:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: publici-artifacts
      ARTIFACT_DIR: /tmp/release/
    steps:
      - id: validate-inputs
        shell: python
        run: |
          allowed = {
            "terraform-modules": "terraform"
          }

          repository = "${{ github.event.repository.name }}"
          input_type = "${{ inputs.type }}"

          expected = allowed[repository]

          if input_type != expected:
            print("Invalid package type: " + input_type)
            exit(1)
      - id: gcp-authenticate
        uses: google-github-actions/auth@v0
        with: 
          workload_identity_provider: projects/318349477291/locations/global/workloadIdentityPools/publici-share-github/providers/publici-share-github
          service_account: gh-actions@publici-apps.iam.gserviceaccount.com
      - id: download-asset
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_id }}
          path: /tmp/release/
      - id: upload-release-asset
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: /tmp/release/
          destination: |
            ${{ env.BUCKET_NAME }}/${{ inputs.type }}/${{ inputs.package }}/${{ inputs.artifact_id }}
